adding test report

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -57,7 +57,14 @@ jobs:
     - name: Build
       run: dotnet build --no-restore  --verbosity m --configuration Release /p:Version=${{ steps.versioner.outputs.Version }}
     - name: Test
-      run: dotnet test --no-build --configuration Release
+      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: NUnit Tests            # Name of the check run which will be created
+        path: TestResults/test-results.trx    # Path to test results
+        reporter: dotnet-trx        # Format of test results
     - name: Copy generated nuget file
       run: find . -name "SystemTestingTools*.nupkg" -exec cp "{}" ./  \;
     - name: Set nuget package artifact
